### ISSUE TITLE
Pageobject.mergePage() fails for some pages with images

### ISSUE THREAD

**Issue by Eipaeipa** [mstamy2/PyPDF2#176]
I was trying to add page numbers to a pdf, it works for most pages of my pdf-document, but it fails for some (with images), producing the following Traceback:

>>> addPagenumbers(abc)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 7, in addPagenumbers
  File "C:\Python34\lib\site-packages\PyPDF2\pdf.py", line 2013, in mergePage
    self._mergePage(page2)
  File "C:\Python34\lib\site-packages\PyPDF2\pdf.py", line 2085, in _mergePage
    self[NameObject('/Contents')] = ContentStream(newContentArray, self.pdf)
  File "C:\Python34\lib\site-packages\PyPDF2\pdf.py", line 2443, in __init__
    data += s.getObject().getData()
  File "C:\Python34\lib\site-packages\PyPDF2\generic.py", line 808, in getData
    return self._data
  File "C:\Python34\lib\site-packages\PyPDF2\pdf.py", line 2535, in _getData
    op.writeToStream(newdata, None)
AttributeError: 'str' object has no attribute 'writeToStream'

**Comment by akaiame** [comment]
I'm getting the same exact error with some pages. I have the same project for both python 3 and python 2, but this error ONLY happens in python 3! In one case, I have a set of pdfs that I run through a downsampling script first before merging. For that case, the error only happens if I use that downsampling script, but it merges fine if I don't downsample. My downsampling script converts CMYK to RGB, downsamples images, and a few other things, using GhostScript. The pdfs I've used that cause this I believe are all pdf version 1.7 if that helps.

There is already an issue with Python 3 compatibility in filters.py, so I wonder if this could be related to compatibility problems? @Eipaeipa what version are you using of PyPDF2 and Python? Mine are:
PyPDF2 1.24
Python 3.4.2

**Comment by Eipaeipa** [comment]
I use the following versions:
PyPDF2 1.24 with an updated filters.py (only the ASCII85Decode function for python3 compatibility)
Python 3.4.3

I could solve my problem by reprinting the pdfs using the adobe pdf tool instead of the freepdf writer or the cutePDF writer. I couldn't find which pdf versions are created by these programs.

**Comment by tiznull** [comment]
We have this same issue, any chances of getting it corrected?

**Comment by mstamy2** [comment]
Some Python 3 issues in filters.py have been corrected; has this solved any of your issues? If not, I'll look into it again - providing any of the offending PDFs (if allowable) would help.

**Comment by claird** [comment]
Hello,

Thank you for your question, comments, and/or concerns regarding PyPDF2.
All of our PyPDF2 users are very important to us.  Unfortunately at this
present time we are in the process of regrouping our office.  Your
questions are very important to us but regretfully we will not be able to
address any issues regarding PyPDF2 until later this fall.  However, if
this is an urgent matter and you need immediate assistance please respond
to this email and we will try our best to accommodate your needs sooner.
My apologies for the inconvenience.  Thank you for your patience.

Sincerely,

Selma Kishwar

Phaseit, Inc.

selmaikishwar@gmail.com
