### ISSUE TITLE
AttributeError: 'unicode' object has no attribute 'write' when passing in a unicode filename to merger.write

### ISSUE THREAD

**Issue by troyshu** [mstamy2/PyPDF2#191]
Not sure where else this occurs, but noticed that a PdfFileMerger can't handle the case where a unicode filename string is passed into merge(). E.g this fails (passing in u"test.pdf"), throwing a ```AttributeError: 'unicode' object has no attribute 'write'```:

```python
from PyPDF2 import PdfFileMerger, PdfFileReader
merger = PdfFileMerger(strict=False)
for filename in filenames:
    merger.append(PdfFileReader(file(filename, 'rb')))

merger.write(u"test.pdf")
```

While this succeeds:

```python
from PyPDF2 import PdfFileMerger, PdfFileReader
merger = PdfFileMerger(strict=False)
for filename in filenames:
    merger.append(PdfFileReader(file(filename, 'rb')))

merger.write("test.pdf")
```

Doesn't seem like expected behavior?

**Comment by dhudson1** [comment]
The reason that this occurs is that Unicode strings (type '```unicode```') aren't really Python's default string (type '```str```').

To confirm this, simply plug and chug the following lines:
```python
unicode_string = u'Hello, world!'
ascii_string = 'Hello, world!'
print(type(ascii_string))
print(type(unicode_string))
```

This issue is only with Python 2.X. Since I use Python 3.X, I was unable to test this, or several of the following lines of code.

If you really need to pass the Unicode string into the merger's write function and not an already opened file object, you could just make a little Unicode to ASCII conversion if statement within the ```write``` method. An example:
```python
if isinstance(fileobj, unicode):
     fileobj = fileobj.encode('utf8')
```

If you do decide to go with the above example, insert those lines of code between the initial definition of ```my_file``` and the ```if``` statement immediately following, and it should work like expected, but only if your file names follow the UTF-8 encoding scheme.

The reason for this exception is that PyPDF2 assumes that you pass it either an instance of the ```str``` class or an instance of the ```file``` class. Since an instance of the ```unicode``` class is neither of those and since PyPDF2 assumes that ```fileobj``` is a file if not a string, PyPDF2 calls the ```write``` function, thinking that ```fileobj``` is an instance of the ```file``` class, which leads to that particular error you were experiencing.

**Comment by troyshu** [comment]
Appreciate the explanation! I had gone with the unicode to ascii conversion, forgot that this was still open until you commented.

**Comment by claird** [comment]
Hello,

Thank you for your question, comments, and/or concerns regarding PyPDF2.
All of our PyPDF2 users are very important to us.  Unfortunately at this
present time we are in the process of regrouping our office.  Your
questions are very important to us but regretfully we will not be able to
address any issues regarding PyPDF2 until later this fall.  However, if
this is an urgent matter and you need immediate assistance please respond
to this email and we will try our best to accommodate your needs sooner.
My apologies for the inconvenience.  Thank you for your patience.

Sincerely,

Selma Kishwar

Phaseit, Inc.

selmaiksihwar@gmail.com
