### ISSUE TITLE
PdfReadError: Multiple definitions in dictionary at byte 0x30b for key /Type

### ISSUE THREAD

**Issue by milspect18** [mstamy2/PyPDF2#244]
When attempting to merge multiple PDF documents, the merger.write("foo.pdf") line chokes with the error shown in the title...  I was attempting to merge a few files with the following:

<pre><code>
import PyPDF2 as PDF
import glob

allPdfFiles = glob.glob("*.pdf")
merger = PDF.PdfFileMerger()

for filename in allPdfFiles:
    merger.append(PDF.PdfFileReader(filename, "rb"))

merger.write("merged_full.pdf")
</code></pre>

The output is as follows:

<pre><code>
Traceback (most recent call last):
  File "C:\Users\kprice\Google Drive\AC201\RawChapters\CH3\pdfMerge.py", line 10, in <module>
    merger.write("merged_full.pdf")
  File "C:\Python27\lib\site-packages\PyPDF2\merger.py", line 230, in write
    self.output.write(fileobj)
  File "C:\Python27\lib\site-packages\PyPDF2\pdf.py", line 467, in write
    self._sweepIndirectReferences(externalReferenceMap, self._root)
  File "C:\Python27\lib\site-packages\PyPDF2\pdf.py", line 556, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "C:\Python27\lib\site-packages\PyPDF2\pdf.py", line 532, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Python27\lib\site-packages\PyPDF2\pdf.py", line 556, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "C:\Python27\lib\site-packages\PyPDF2\pdf.py", line 532, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Python27\lib\site-packages\PyPDF2\pdf.py", line 541, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, data[i])
  File "C:\Python27\lib\site-packages\PyPDF2\pdf.py", line 556, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "C:\Python27\lib\site-packages\PyPDF2\pdf.py", line 532, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Python27\lib\site-packages\PyPDF2\pdf.py", line 532, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Python27\lib\site-packages\PyPDF2\pdf.py", line 532, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Python27\lib\site-packages\PyPDF2\pdf.py", line 561, in _sweepIndirectReferences
    newobj = data.pdf.getObject(data)
  File "C:\Python27\lib\site-packages\PyPDF2\pdf.py", line 1582, in getObject
    retval = readObject(self.stream, self)
  File "C:\Python27\lib\site-packages\PyPDF2\generic.py", line 66, in readObject
    return DictionaryObject.readFromStream(stream, pdf)
  File "C:\Python27\lib\site-packages\PyPDF2\generic.py", line 581, in readFromStream
    % (utils.hexStr(stream.tell()), key))
PdfReadError: Multiple definitions in dictionary at byte 0x30b for key /Type
</code></pre>

**Comment by lambdalisue** [comment]
+1. Same here

**Comment by pokey** [comment]
For me, @lambdalisue's solution didn't work.  I instead had to do:

```
merger = PdfFileMerger(strict=False)
```

**Comment by jwhendy** [comment]
Could someone clarify this if this is a "bug" or not? I ran into this when using [stapler](https://github.com/fwenzel/stapler/issues/7), but don't know how to view what's going on. For example:

- perhaps multiple `/Type` definitions doesn't play well with `pypdf2`
- multiple `/Type` definitions aren't expected/shouldn't be in a "proper" pdf file and that's why it complains
- multiple `/Type` definitions is valid for pdfs but `pypdf2` doesn't handle them currently via it's algorithm. Eventually it could handle them, but presently chokes a bit with a `strict=True` setting. This ends up not being fatal and thus we can bypass with `strict=False`

I'm just trying to understand what to do about the errors, if there are unintended side effects, if this will be "fixed" at some point... for what it's worth, before figuring out I could use `strict=False`, I used [pdfunite](http://stackoverflow.com/questions/2507766/merge-convert-multiple-pdf-files-into-one-pdf) just fine; I don't understand why that's fine but this had troubles with my input.

**Comment by yw5aj** [comment]
+1 for having this issue and fixed by `merger = PdfFileMerger(strict=False)`. It does give out a warning `PdfReadWarning: Multiple definitions in dictionary at byte 0x2d72 for key /Type [generic.py:589]` instead of error `PdfReadError: Multiple definitions in dictionary at byte 0x2d72 for key /Type` though.

**Comment by radzhome** [comment]
+1

**Comment by Paul424** [comment]
Thanks for the tip; it worked!

**Comment by akkana** [comment]
+1. I used the provided example in Sample_Code/basic_merging.py, and then pared it down to two PDF files which were each just called with append(fileobj), and it still didn't work. The workaround of PdfFileMerger(strict=False) solves the problem (modulo a bunch of warning messages). It would help to have the basic_merging example mention strict=False since it looks like that's needed for many (maybe all?) real-world PDF files.

**Comment by lunikernel** [comment]
I tripped over this.  If its all the same to the outcomes then it would be good if this fix was the default.

**Comment by charalamm** [comment]
Hello,
Could someone explain which sepecific thing inside a pdf could cause this error/warning?
Thank you :)

**Comment by tripleee** [comment]
A PDF file is a (constrained) PostScript program. The error (or warning) means that the program attempted to redefine an internal dictionary variable. The fact that this often happens while merging would suggest that both the merged documents wanted to use the same variable name, resulting in this conflict when you combine them. There isn't really anything you can do (especially on the Python side) to reconcile this in a document which somebody else created.

**Comment by Ontheroad123** [comment]
Through i add the param 'strict', it still print "Multiple definitions in dictionary at byte 0x51d16 for key /MediaBox", and some txt may messy code, how can i solve it?

**Comment by pubpub-zz** [comment]
a) Strict shall be set
b) without pdf and code no analysis can be done

you should open a new issue providing those details
