### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by eamanu** [mstamy2/PyPDF2#510]
Hello everybody, 

I would like to know if this project is still active. I read some related issue like #373 and the discussion on #385, but I don't see a lot of movement on the Project. 

I can see some PR that didn't have response.

**Comment by clach04** [comment]
I don't know. There is a pyPDF3 by the same author which has been updated more recently at https://github.com/mstamy2/PyPDF3

I also found (by clicking through the fork graph) https://github.com/claird/PyPDF4 which was updated a few months ago. The API is similar, but slightly different (meta data appears to be more Pythonic with respect  to using properties, rather than method calls).

**Comment by eamanu** [comment]
I did not the PyPDF4, thanks for the information. 

I according to libraries.io PyPDF2 [1] has more user than PyPDF3 [2] and PyPDF4 [3]. Maybe PyPDF2 reached a certain maturity that does not need significant changes.

I will close this issue.
